language: node_js
node_js:
  - "0.12"
  - "0.10"
addons:
  code_climate:
    repo_token: 156df97e7b5f16aec0010e19766e7fd1e823c4c8691ee17f97ba4e2546b58b4b
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info; rm -rf ./coverage;
